export class Hocsinh {
    mahocsinh:string;
    hoten:string;
    gioitinh:string;
    ngaysinh:string;
    diachi:string;
    dienthoai:string;
    dantoc:string;
    tongiao:string;
    ngayvaodoan:string;
    noisinh:string;
    cmnd:string;
    malop:string;
    hotenBo:string;
    hotenMe:string;
    dienthoaiBo:string;
    dienthoaiMe:string;
    dvCongTacBo:string;
    dvCongTacMe:string;
    nguoidamho:string;
    anh:string;
    email:string;
}
